/** @type {import('tailwindcss').Config} */
export default {
    content: [
      "./index.html",
      "./src/**/*.{js,ts,jsx,tsx}",
    ],
    darkMode: "class",
    theme: {
      extend: {
        colors: {
          "on-tertiary-fixed": "#003840",
          "tertiary-fixed": "#0fe3ff",
          "outline": "#767575",
          "on-secondary-fixed-variant": "#6300e2",
          "on-secondary-fixed": "#41009a",
          "background": "#0e0e0e",
          "on-error": "#450900",
          "on-background": "#ffffff",
          "on-tertiary-container": "#004d58",
          "error-container": "#b92902",
          "surface-variant": "#262626",
          "on-surface-variant": "#adaaaa",
          "on-primary": "#00663e",
          "inverse-on-surface": "#565555",
          "secondary-fixed": "#dac9ff",
          "tertiary-container": "#0fe3ff",
          "surface-container-low": "#131313",
          "surface-tint": "#b1ffce",
          "inverse-surface": "#fcf9f8",
          "surface-container": "#1a1a1a",
          "on-primary-container": "#005c38",
          "surface-bright": "#2c2c2c",
          "surface-container-lowest": "#000000",
          "secondary-fixed-dim": "#ceb9ff",
          "tertiary-fixed-dim": "#00d4ee",
          "on-tertiary-fixed-variant": "#005763",
          "error": "#ff7351",
          "primary-fixed": "#00ffa3",
          "surface": "#0e0e0e",
          "error-dim": "#d53d18",
          "surface-dim": "#0e0e0e",
          "primary": "#b1ffce",
          "surface-container-highest": "#262626",
          "inverse-primary": "#006d43",
          "primary-fixed-dim": "#00ef99",
          "secondary-container": "#7000ff",
          "on-primary-fixed": "#00472a",
          "on-secondary-container": "#f8f1ff",
          "secondary": "#ac89ff",
          "surface-container-high": "#20201f",
          "tertiary-dim": "#00d4ee",
          "on-primary-fixed-variant": "#00673f",
          "on-surface": "#ffffff",
          "on-secondary": "#290067",
          "tertiary": "#88ebff",
          "primary-dim": "#00ef99",
          "outline-variant": "#484847",
          "secondary-dim": "#874cff",
          "on-error-container": "#ffd2c8",
          "on-tertiary": "#005762",
          "primary-container": "#00ffa3"
        },
        borderRadius: {
          "DEFAULT": "0.25rem",
          "lg": "0.5rem",
          "xl": "0.75rem",
          "full": "9999px"
        },
        fontFamily: {
          "headline": ["Be Vietnam Pro"],
          "body": ["Manrope"],
          "label": ["Manrope"]
        }
      },
    },
    plugins: [],
  }
